POST http://localhost:8080/board-game HTTP/1.1
content-type: application/json

{
    "name": "Mastermind",
    "pieces": {
        "decodingBoard": {
            "totalCount": 1
        },
        "pegs": {
            "totalCount": 102,
            "types": [
                {
                    "type": "code",
                    "count": 72
                },
                {
                    "type": "key",
                    "count": 31
                }
            ]
        },
        "rulebook": {
            "totalCount": 1,
            "file": "rulebook-ultimate-mastermind.pdf"
        }
    }
}

###
GET http://localhost:8080/board-game/633f2a8e HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8080/board-game/861015ed HTTP/1.1
content-type: application/json

{
    "name": "Mastermind",
    "pieces": {
        "decodingBoard": {
            "totalCount": 2
        },
        "pegs": {
            "totalCount": 103,
            "types": [
                {
                    "type": "code",
                    "count": 100
                },
                {
                    "type": "key",
                    "count": 200
                }
            ]
        },
        "rulebook": {
            "totalCount": 3,
            "file": "rulebook-ultimate-mastermind.pdf"
        }
    },
    "id": "861015ed",
    "insertCount": 0,
    "updateCount": 0,
    "upsert": false
}

###

GET http://localhost:8080/board-game/d4d4e2b1 HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/board-game/list HTTP/1.1
content-type: application/json